// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-VNu0nraKLX921wfo0xlAETvSnezKCSA',
    appId: '1:534654186450:web:6c63eb1660afd41fba8e0b',
    messagingSenderId: '534654186450',
    projectId: 'classroom-75d8f',
    authDomain: 'classroom-75d8f.firebaseapp.com',
    storageBucket: 'classroom-75d8f.appspot.com',
    measurementId: 'G-R7676GHN7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuW4dw6QbPc9QJwYAHltnrDtvBTfUeB04',
    appId: '1:534654186450:android:c1708c45dad3296cba8e0b',
    messagingSenderId: '534654186450',
    projectId: 'classroom-75d8f',
    storageBucket: 'classroom-75d8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARBNc6IJnk7pHvfy8G0BHPX09fkmYUthM',
    appId: '1:534654186450:ios:466e45c9dd7a6ef8ba8e0b',
    messagingSenderId: '534654186450',
    projectId: 'classroom-75d8f',
    storageBucket: 'classroom-75d8f.appspot.com',
    iosBundleId: 'com.example.jemaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARBNc6IJnk7pHvfy8G0BHPX09fkmYUthM',
    appId: '1:534654186450:ios:8ffcae2dcde0109fba8e0b',
    messagingSenderId: '534654186450',
    projectId: 'classroom-75d8f',
    storageBucket: 'classroom-75d8f.appspot.com',
    iosBundleId: 'com.example.jemaApp.RunnerTests',
  );
}
